# Generated by Django 3.0.4 on 2020-03-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='date_of_birth',
            new_name='ngay_sinh',
        ),
    ]
