# Generated by Django 3.0.4 on 2020-03-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_null_true', models.CharField(max_length=50, null=True)),
                ('title_blank_true', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=150)),
                ('author', models.CharField(editable=False, max_length=20)),
            ],
        ),
    ]
