# Generated by Django 3.0.4 on 2020-03-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
