# Generated by Django 3.0.4 on 2020-03-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_date_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_blank_true',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_null_true',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
